language: python
cache: pip
python:
  - "3.6"
  - "3.7"
  - "3.8-dev"
install:
  - make install-dev
  - pip install coveralls
script:
  - make ci
after_script:
  - if [[ "$TRAVIS_PULL_REQUEST" == "false" && "$TRAVIS_PYTHON_VERSION" == "3.6" ]]; then coveralls; fi
